### ISSUE TITLE
Fake && Empty

### ISSUE THREAD

**Issue by hobbydev71** [PinataCloud/React-IPFS-Example#1]
Who starred this?

**Comment by jaller94** [comment]
This is a boilerplate repository from which people can more easily start their own React projects.
It allows you to clone the repo and immediately start writing your own components without having to worry about dependencies at first.

It's not fake and it's sort of empty by design.

**Comment by hobbydev71** [comment]
Then, you might remove the IPFS from repository name.

**Comment by obo20** [comment]
@hobbydev71 the reason this has IPFS in the title is that the project is specifically configured to be compatible with serving from IPFS from a gateway. 

This blog post explains the configuration changes: https://medium.com/pinata/how-to-easily-host-a-website-on-ipfs-9d842b5d6a01

While the changes are relatively small, we wanted to make sure our readers had an accurate boiler plate to work from if desired.
